### ISSUE TITLE
Strong name signature could not be verified

### ISSUE THREAD

**Issue by raphaotten** [agnauck/XmppDotNet#34]
I get the error message "Strong name signature could not be verified" when using XmppDotNet.Core in a MVC .NET Framework project.

The verification in a VS Developer Command Prompt fails: 

```
>sn.exe -v  .\XmppDotNet.Core.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.

```

It also happens for all other DLLs : XmppDotNet.dll  etc.

How can it be fixed?

**Comment by agnauck** [comment]
Are you on legacy .NET or netCore?
No issues here, its tells me the assemblies are fine:

![image](https://github.com/agnauck/XmppDotNet/assets/1344950/30ec59ee-ee9d-4548-bc2f-b279d4f8318d)

**Comment by raphaotten** [comment]
Legacy .NET (.NET Framework 4.8, for one of the projects, where I see the error).

If I clone the repository, build (Debug) then I also receive valid DLL files.
If I include the nuget in the project, then the resulting XMPPDotNet DLLs are not valid.

**Comment by agnauck** [comment]
is it using then the netStandard 2.0 or 2.1 builds?

The nugets are just getting build from the CI, but using a very recent netCore version.

**Comment by raphaotten** [comment]
It is using the netstandard2.0 build. But using "sn -v" all versions (also .NET 6 & 8) in the packages/XmppDotNet.3.2.2/lib/ folder seem to be invalid  (packages/XmppDotNet.3.2.2/lib/net8.0/XmppDotNet.dll, packages/XmppDotNet.3.2.2/lib/netstandard2.1/XmppDotNet.dll, etc.)

**Comment by agnauck** [comment]
its possible that its related to this line:
https://github.com/agnauck/XmppDotNet/blob/80e6f0cc2350c261705f1c5b7595cb3510cc4bb5/.build/sign.props#L5

Because the CI runs on Linux.
Would need to research this in more.....

**Comment by raphaotten** [comment]
I am not sure actually :-(

Seems like the DLLs get downloaded from here: https://api.nuget.org/v3-flatcontainer/xmppdotnet.core/3.2.2/xmppdotnet.core.3.2.2.nupkg
This is an archive and can be opened. The containing DLLs seem to be not signed correctly.

**Comment by raphaotten** [comment]
> its possible that its related to this line:
> 
> https://github.com/agnauck/XmppDotNet/blob/80e6f0cc2350c261705f1c5b7595cb3510cc4bb5/.build/sign.props#L5
> 
> Because the CI runs on Linux. Would need to research this in more.....

Seems like the 'normal' signing on Linux was a problem in the past. But it is possible for several years now.
see https://github.com/dotnet/roslyn/issues/8210

**Comment by agnauck** [comment]
ya signing is not really used anymore that much on netcore.

However, I a pushed a branch and updated the CI to use a Windows image instead of Ubuntu.
You can checkout the CI builds here and give feedback:
https://www.myget.org/feed/Packages/xmppdotnet

**Comment by raphaotten** [comment]
![image](https://github.com/agnauck/XmppDotNet/assets/1467334/925ebfc9-83f8-4d6a-aece-860c4203a1be)
the new binaries still don't  succeed in the test.

The WebApp doesn't start and still looks like this as a result:
![image](https://github.com/agnauck/XmppDotNet/assets/1467334/b69f0198-b9c8-4335-964a-917791953b98)

**Comment by agnauck** [comment]
I will update Ci to use Windows again later today and generate new packages.
Will then decide later on what to do with signing.

**Comment by agnauck** [comment]
https://github.com/agnauck/XmppDotNet/pull/35 is merged.
Version 3.2.3 should show up on Nuget soon
